[project]
name = "mcp-course-hf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.12",
    "gradio>=5.49.1",
    "mcp>=1.20.0",
    "requests>=2.32.5",
]
