[project]
name = "cluas"
version = "0.1.0"
description = "a dialectic deliberation engine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.1",
    "feedparser>=6.0.12",
    gradio = { version = "6.0.0.dev4", extras = ["mcp", "oauth"] },
    "groq>=0.36.0",
    "mcp>=1.20.0",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "tenacity>=9.1.2",
]


